### ISSUE TITLE
'vagrant up' does not work

### ISSUE THREAD

**Issue by johnchadwick** [settermjd/zf2forbeginners#1]
In Windows 8, I cloned the code to c:\ and the files are in the c:\zf2forbeginners directory. I installed VirtualBox and Vagrant. Then using the command line I cd to zf2forbeginners and enter:
vagrant up
Then it shows this:
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.

Thanks,
John

**Comment by settermjd** [comment]
John, sorry for the delay in getting back on this. I'll check it out through the day tomorrow. Thanks for letting me know.

**Comment by johnchadwick** [comment]
Hi Matthew:
No problem. So far I like your book. Good explanations and excellent links.
Right now it looks like I'll be posting a number of issues. Let me know if you want me to continue posting at the above url or just email you like this. If you frequently fix issues, I think your book will become very popular, since beginners really get stuck on errors.
Questions / issues:
Question: Mockery is listed as required but I searched the book and your code for the term 'mockery' and could not find it. According to Mockery installation notes one would use something like 'require-dev' and '"mockery/mockery": "dev-master"', see:https://github.com/padraic/mockery/blob/master/docs/01-INSTALLATION.md
page 23:I can't see "test" folder in the Zend skeleton application. Maybe it has to be created as in Zend's tutorial that I went through:http://framework.zend.com/manual/2.0/en/user-guide/unit-testing.html
page 31, just a little link error:http://de3.php.net/manual/en/functions.anonymous.phpworks:http://php.net/manual/en/functions.anonymous.php
I get "No tests executed".  Since you emailed me today I thought I'd include this one. I will continue to look at it since I am not sure if I made an error but a few things I noticed:Page 51:  Module is ControllerTest.php, yet you show "class RoutingTest extends AbstractHttpControllerTestCase"The methods on page 52 in public function testFeedHomePageCanBeAccessed are in AbstractControllerTestCase rather than AbstractHttpControllerTestCase. Same thing here: http://framework.zend.com/manual/2.3/en/tutorials/unittesting.html and many people having issues with PHPUnit. As an aside, I noticed that "abstract class AbstractControllerTestCase extends PHPUnit_Framework_TestCase" class but this class does not exist. PHPStorm is great, as it alerts me to undefined classes.
Regards,
John
Date: Thu, 16 Oct 2014 10:34:53 -0700

**Comment by settermjd** [comment]
Hi again John. I've been a bit slow getting in to this as I've been trying to catching up after a long deserved holiday. It'll take me a little while to work through all this, but I appreciate you for adding it all. If you have other issues, if they're related, please add them here. Otherwise, please add them separately in related groups. That way it's easier to make sense of and correct.

**Comment by johnchadwick** [comment]
I redid it and got the 2 test failures as expected. The first failer being "BabyMonitorTest\Controller\RoutingTest::testFeedHomePageCanBeAccessed
13 Failed asserting response code "200", actual status code is "404"". Not sure what went wrong. This time used bootstrap.php from here: http://framework.zend.com/manual/2.3/en/tutorials/unittesting.html since I'm using 2.3. It looks nearly identical. Thanks.

**Comment by johnchadwick** [comment]
Actually there is only 1 test, testFeedHomePageCanBeAccessed. The second test mentioned on page 54 "testFeedManagePageCanBeAccessed" was never created. From now on I'll post new issues separately.

**Comment by settermjd** [comment]
Thanks @johnchadwick

**Comment by settermjd** [comment]
@johnchadwick, after checking out the code, I see that I didn't add in the h1 header and that consequently the tests still fail. Commit b7a298da7 corrects the issue and the test feed manage page test was added in commit dc702a95c05e14430d42ea58011e8a0a69681af4.

**Comment by settermjd** [comment]
@johnchadwick with respect to having issues with Vagrant, you don't need it and there's no Vagrantfile in the project. Instead, start the app using PHP's built in web server by running the following command `php -S localhost:8080 -t public` from the root directory of the project.

**Comment by settermjd** [comment]
If you want to work with Vagrant, feel free to. I may add a specific guide in the future, or in a future release of the book. In the meantime, checkout the [PuPHPet](http://www.puphpet.com) project. That gives you a handy wizard for generating Vagrant/VirtualBox setups without you having to know a lot about either.

**Comment by settermjd** [comment]
As for mockery, I've just updated the book and am releasing a new version of the book tomorrow removing mention of Mockery until it's included later in the year with a further release.

**Comment by settermjd** [comment]
If you're happy that everything's resolved, let me know and I'll close the ticket.

**Comment by johnchadwick** [comment]
If you update the pdf, how do I download it without purchasing? Changes look good, though I'm not using your completed code, just working my way through your book. I'm not sure if you corrected those little errors above the book (page 23, page 31, Page 51) but that's up to you. Odd how on page 47 the PHPUnit test will not continue past the first error despite the spec in the XML: stopOnError="false" stopOnFailure="false" stopOnIncomplete="false" stopOnSkipped="false". Maybe a bug with PHPUnit. I run the phpunit tests from within PHPStorm now, much nicer. Thanks.

**Comment by settermjd** [comment]
John,

Great to see things are getting better. I'll get back to you about the book
download. As for the possible PHPUnit bug, I'll need to research that one.

Matt

Am Freitag, 24. Oktober 2014 schrieb johnchadwick :

> If you update the pdf, how do I download it without purchasing? Changes
> look good, though I'm not using your completed code, just working my way
> through your book. I'm not sure if you corrected those little errors above
> the book (page 23, page 31, Page 51) but that's up to you. Odd how on page
> 47 the PHPUnit test will not continue past the first error despite the spec
> in the XML: stopOnError="false" stopOnFailure="false"
> stopOnIncomplete="false" stopOnSkipped="false". Maybe a bug with PHPUnit. I
> run the phpunit tests from within PHPStorm now, much nicer. Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/settermjd/zf2forbeginners/issues/1#issuecomment-60333676
> .

## 

Von Gmail Mobile gesendet
