### ISSUE TITLE
When editing record, Float validation somehow causes this warning

### ISSUE THREAD

**Issue by johnchadwick** [settermjd/zf2forbeginners#12]
Try changing to a whole number. (e.g. '5' is a problem, '5.1' is not)
Unknown: grapheme_substr: start not contained in string in Unknown on line 0
Zend\Stdlib\StringWrapper\Intl\strpos

I found this error has happened in other applications so it could be a bug in zend.

**Comment by settermjd** [comment]
@johnchadwick thanks for letting me know. I wasn't aware of that one.
