### ISSUE TITLE
FeedsController function getPaginator must look in class rather than array

### ISSUE THREAD

**Issue by johnchadwick** [settermjd/zf2forbeginners#16]
I am using "Develop" branch, rather than "Master" branch since it is newer.

In FeedsController you look for ResultSetInterface but you look in an array which gives an error:
} elseif (in_array('\Zend\Db\ResultSet\ResultSetInterface', get_class($resultset))) {
Looking in a class works:
} elseif (is_a($resultset, '\Zend\Db\ResultSet\ResultSetInterface'))) {

**Comment by settermjd** [comment]
I really need to redo this. Thanks for the issue.

**Comment by settermjd** [comment]
@johnchadwick I made a correction based on your suggestion in fcd4c147d1.
